# Site settings
title: Centro de ADN del Paraguay
email: contactar@centroadnparaguay.com
description: >
  El Centro de ADN del Paraguay representa principalmente los servicios genéticos del
  Laboratorio Americano DNA Diagnostic Center - DDC, líder mundial en pruebas de ADN.
  Así mismo, también hemos establecido convenios comerciales con otros laboratorios
  genéticos de prestigio, a fin de ampliar la variedad de nuestras pruebas genéticas.
  Gracias a estas estratégicas alianzas comerciales, el Centro de ADN del Paraguay
  puede ofrecer revolucionarias pruebas de ADN que sean altamente confiables,
  confidenciales, seguras y de bajo costo.

baseurl: "/" # the subpath of your site, e.g. /blog/
url: http://www.centroadnparaguay.com # the base hostname & protocol for your site

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: readable

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
